tenant:
  hostname: "env608865.int-aws-de.webmethods.ios"   # webMthodsIO Integration hostname or ip address
  port: "443"                                       # webMthodsIO Integration port
  admin_username: "shilpa.mohanty@softwareag.com"                     # webMthodsIO Integration user
  type: "play"                                         #Dev
